/**
 * aiFoundationsNoobBlock4.ts — NOOB Block 4 (Ch 16–20): Linear Algebra for AI
 * Run: cd backend && npm run seed:af-noob-b4
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
function q(text:string,options:{id:string;text:string}[],correctAnswer:string,explanation:string,orderIndex:number){return{text,options:JSON.stringify(options),correctAnswer,explanation,orderIndex};}
const COURSE_SLUG='foundations';

const CHAPTERS=[
  {slug:'af-noob-16-vectors',title:'Vectors & Geometric Intuition',description:'Vectors as arrows in space, addition, scalar multiplication, dot product, magnitude, and unit vectors — the building blocks of embeddings.',orderIndex:16,xpReward:70,difficulty:'BEGINNER',tier:'NOOB',language:'python',
  content:`# Chapter 16 — Vectors & Geometric Intuition\n\n## What is a Vector?\n\nA vector is an ordered list of numbers with direction and magnitude.\n\n\`\`\`python\nimport numpy as np\nv = np.array([3.0, 4.0])  # 2-D vector\n\`\`\`\n\n## Operations\n\n| Operation | Formula | Meaning |\n|-----------|---------|----------|\n| Addition | v + u | Combine directions |\n| Scalar multiply | 2 * v | Scale magnitude |\n| Dot product | v · u | Projection / similarity |\n| Magnitude | ‖v‖ = √(v·v) | Length |\n| Unit vector | v / ‖v‖ | Direction only |\n\n## Dot Product & Angle\n\n$$\\mathbf{v} \\cdot \\mathbf{u} = \\|v\\|\\|u\\|\\cos(\\theta)$$\n\nCosine similarity = dot product of unit vectors.\n\n## Why Vectors Matter in AI\n\nWord embeddings, image features, model weights, and gradients are ALL vectors. Operations on them define how models learn.`,
  codeExample:`import numpy as np\n\nv1=np.array([3.0,4.0])\nv2=np.array([1.0,2.0])\n\nprint("=== Vector Operations ===")\nprint(f"v1         : {v1}")\nprint(f"v2         : {v2}")\nprint(f"v1+v2      : {v1+v2}")\nprint(f"2*v1       : {2*v1}")\nprint(f"|v1|       : {np.linalg.norm(v1):.4f}")\nprint(f"unit v1    : {v1/np.linalg.norm(v1)}")\nprint(f"dot(v1,v2) : {np.dot(v1,v2):.4f}")\n\ncos_sim = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))\nprint(f"cosine sim : {cos_sim:.4f}")\n\n# Word embedding analogy (simplified)\nprint("\\n=== Embedding Example ===")\nking   = np.array([0.8,0.3,0.1])\nman    = np.array([0.5,0.1,0.0])\nwoman  = np.array([0.5,0.1,0.9])\nqueen  = king - man + woman\nprint(f"king-man+woman = {np.round(queen,3)} ≈ queen embedding")`,
  questions:[
    q('What is the dot product of [1,0] and [0,1]?',[{id:'a',text:'1'},{id:'b',text:'0'},{id:'c',text:'-1'},{id:'d',text:'undefined'}],'b','Perpendicular unit vectors have dot product 0 — zero projection.',0),
    q('What does the unit vector represent?',[{id:'a',text:'The magnitude of a vector'},{id:'b',text:'Direction only — magnitude scaled to 1'},{id:'c',text:'The inverse of a vector'},{id:'d',text:'A vector with zero magnitude'}],'b','Unit vector = v / ‖v‖ preserves direction while normalising length to 1.',1),
    q('What is ‖[3, 4]‖ ?',[{id:'a',text:'7'},{id:'b',text:'12'},{id:'c',text:'5'},{id:'d',text:'25'}],'c','L2 norm = √(3²+4²) = √25 = 5.',2),
    q('What does cosine similarity measure?',[{id:'a',text:'Euclidean distance'},{id:'b',text:'The angle between two vectors — semantic similarity'},{id:'c',text:'Vector magnitude'},{id:'d',text:'Sum of elements'}],'b','cosine = dot(u,v)/(‖u‖‖v‖) — 1 = same direction, 0 = perpendicular.',3),
    q('In word embeddings, why are words represented as vectors?',[{id:'a',text:'To reduce storage'},{id:'b',text:'So that arithmetic captures semantic relationships (king-man+woman≈queen)'},{id:'c',text:'Because neural networks only accept numbers'},{id:'d',text:'Both B and C'}],'d','Vectors enable semantic arithmetic and allow neural networks to process language numerically.',4),
    q('What does scalar multiplication of 2*v do geometrically?',[{id:'a',text:'Rotates the vector'},{id:'b',text:'Doubles the length, same direction'},{id:'c',text:'Halves the length'},{id:'d',text:'Flips direction'}],'b','Scalar multiplication scales the magnitude — direction unchanged for positive scalar.',5),
    q('Which operation computes the sum of element-wise products of two vectors?',[{id:'a',text:'Cross product'},{id:'b',text:'Outer product'},{id:'c',text:'Dot product'},{id:'d',text:'Hadamard product'}],'c','dot(a,b) = Σ aᵢbᵢ — the sum of element-wise products.',6),
    q('What does a gradient vector point toward?',[{id:'a',text:'The global minimum'},{id:'b',text:'The direction of steepest INCREASE in the loss function'},{id:'c',text:'The origin'},{id:'d',text:'The nearest data point'}],'b','Gradient points toward steepest ascent — we move OPPOSITE for gradient descent.',7),
    q('Vectors in higher dimensions (e.g., 512-D) are used for:',[{id:'a',text:'Storing images as pixels'},{id:'b',text:'Representing words, sentences, and images as dense feature vectors (embeddings)'},{id:'c',text:'Matrix inversion'},{id:'d',text:'Database indexing'}],'b','High-dimensional embeddings capture semantic meaning — fundamental to transformers and recommendation systems.',8),
    q('What is the result of adding two perpendicular unit vectors?',[{id:'a',text:'The zero vector'},{id:'b',text:'A vector of magnitude √2 at 45°'},{id:'c',text:'A unit vector'},{id:'d',text:'undefined'}],'b','|[1,0]+[0,1]| = |[1,1]| = √2, at 45° between the two.',9),
  ]},

  {slug:'af-noob-17-matrices',title:'Matrices & Matrix Operations',description:'Matrix structure, multiplication, transpose, determinant, and rank — the core operations behind every neural network layer.',orderIndex:17,xpReward:70,difficulty:'BEGINNER',tier:'NOOB',language:'python',
  content:`# Chapter 17 — Matrices & Matrix Operations\n\n## Matrix Anatomy\n\nA matrix A of shape (m×n) has m rows and n columns.\n\n\`\`\`python\nimport numpy as np\nA = np.array([[1,2,3],[4,5,6]])  # 2×3\n\`\`\`\n\n## Key Operations\n\n| Op | Symbol | Meaning |\n|----|--------|---------|\n| Transpose | A.T | Swap rows ↔ columns |\n| Element-wise | A * B | Hadamard product |\n| Matrix multiply | A @ B | Linear transformation |\n| Determinant | det(A) | Scalar — volume scaling |\n| Rank | rank(A) | Linearly independent rows/cols |\n\n## Matrix Multiply Rules\n\nA(m×n) @ B(n×p) = C(m×p) — inner dims must match.\n\n## Identity Matrix\n\nI @ A = A @ I = A — like multiplying by 1.\n\n## Why It Matters\n\nEvery dense layer in a neural network computes: Z = W @ X + b`,
  codeExample:`import numpy as np\n\nA = np.array([[1,2],[3,4],[5,6]])   # 3×2\nB = np.array([[7,8,9],[10,11,12]]) # 2×3\nprint(f"A shape: {A.shape}  B shape: {B.shape}")\nC = A @ B  # (3×2)@(2×3) = 3×3\nprint(f"C=A@B:\\n{C}")\nprint(f"A.T:\\n{A.T}")\n\nW = np.random.randn(4,3)\nx = np.random.randn(3,1)\nz = W @ x\nprint(f"\\nNeural layer: W({W.shape}) @ x({x.shape}) = z({z.shape})")\nprint(f"z = {z.T}")\n\nM = np.array([[2,1],[1,3]], dtype=float)\nprint(f"\\nDet(M) = {np.linalg.det(M):.2f}")\nprint(f"Rank(M) = {np.linalg.matrix_rank(M)}")`,
  questions:[
    q('What shape is the result of a (3×4) matrix multiplied by a (4×2) matrix?',[{id:'a',text:'(4×4)'},{id:'b',text:'(3×2)'},{id:'c',text:'(4×3)'},{id:'d',text:'Error'}],'b','(m×n)@(n×p)=(m×p): (3×4)@(4×2)=(3×2).',0),
    q('What does the transpose A.T do?',[{id:'a',text:'Inverts the matrix'},{id:'b',text:'Swaps rows and columns'},{id:'c',text:'Computes the determinant'},{id:'d',text:'Normalises rows to unit length'}],'b','Transpose reflects elements across the main diagonal — rows become columns.',1),
    q('What is the identity matrix I?',[{id:'a',text:'A matrix of all ones'},{id:'b',text:'A matrix with 1s on the diagonal, 0s elsewhere'},{id:'c',text:'The inverse of any matrix'},{id:'d',text:'A matrix of all zeros'}],'b','Identity is the matrix equivalent of the number 1 — A@I = I@A = A.',2),
    q('What does the determinant of a 2×2 matrix measure?',[{id:'a',text:'The sum of all elements'},{id:'b',text:'The area scaling factor of the linear transformation'},{id:'c',text:'The trace'},{id:'d',text:'The rank'}],'b','det = ad-bc for [[a,b],[c,d]] — it measures how the transformation scales areas.',3),
    q('In a neural network dense layer, what does the computation Z = W @ X do?',[{id:'a',text:'Applies activation function'},{id:'b',text:'Linearly transforms input X through weight matrix W'},{id:'c',text:'Computes the loss'},{id:'d',text:'Updates the weights'}],'b','W@X is a linear transformation mapping X from input space to output space.',4),
    q('What does matrix rank measure?',[{id:'a',text:'Number of rows'},{id:'b',text:'Number of linearly independent rows or columns'},{id:'c',text:'Sum of diagonal elements'},{id:'d',text:'Determinant value'}],'b','Rank counts the effective dimension of the column/row space — max independent vectors.',5),
    q('What is the Hadamard (element-wise) product of [[1,2],[3,4]] and [[2,0],[1,3]]?',[{id:'a',text:'[[2,0],[3,12]]'},{id:'b',text:'[[4,4],[6,12]]'},{id:'c',text:'Error'},{id:'d',text:'[[2,6],[4,10]]'}],'a','Hadamard: multiply corresponding elements — [[1*2,2*0],[3*1,4*3]]=[[2,0],[3,12]].',6),
    q('Why must inner dimensions match for matrix multiplication A@B?',[{id:'a',text:'For numerical stability'},{id:'b',text:'Each row of A is dotted with each column of B — this requires equal length'},{id:'c',text:'NumPy requires it for efficiency'},{id:'d',text:'To ensure the result is square'}],'b','A(m×n)@B(n×p): each dot product sums n products — the n dims must match.',7),
    q('Which operation computes gradient update dW = dZ @ X.T?',[{id:'a',text:'Hadamard product'},{id:'b',text:'Matrix multiplication with transpose'},{id:'c',text:'Element-wise division'},{id:'d',text:'Matrix determinant'}],'b','The gradient dW = dZ@X.T aligns shapes for the weight update in backpropagation.',8),
    q('What does a singular matrix (det=0) imply?',[{id:'a',text:'The matrix has full rank'},{id:'b',text:'The matrix has no inverse — rows are linearly dependent'},{id:'c',text:'The matrix is the identity'},{id:'d',text:'The matrix is symmetric'}],'b','det=0 means columns/rows are linearly dependent — the matrix cannot be inverted.',9),
  ]},

  {slug:'af-noob-18-linear-equations',title:'Systems of Linear Equations',description:'Gaussian elimination, matrix form Ax=b, np.linalg.solve, over/under-determined systems, and the connection to Linear Regression normal equations.',orderIndex:18,xpReward:70,difficulty:'BEGINNER',tier:'NOOB',language:'python',
  content:`# Chapter 18 — Systems of Linear Equations\n\n## Matrix Form\n\nA system of equations: Ax = b\n\n\`\`\`\n2x + y = 5\n x + 3y = 10\n\`\`\`\n\nBecomes:\n\`\`\`python\nA = [[2, 1], [1, 3]]\nb = [5, 10]\nx = np.linalg.solve(A, b)  # [1, 3]\n\`\`\`\n\n## Gaussian Elimination\n\nRow-reduce the augmented matrix [A|b] to solve for x.\n\n## Solution Cases\n\n| Case | Meaning |\n|------|---------|\n| Unique solution | A is full rank |\n| No solution | Inconsistent — parallel planes |\n| Infinite solutions | Under-determined |\n\n## Linear Regression Normal Equation\n\nThe closed-form solution: w = (XᵀX)⁻¹Xᵀy\n\nThis IS solving a linear system — gradient descent is just a cheaper iterative alternative.`,
  codeExample:`import numpy as np\n\n# 1. Solve Ax = b\nA = np.array([[2,1],[1,3]], dtype=float)\nb = np.array([5,10], dtype=float)\nx = np.linalg.solve(A, b)\nprint(f"Solution: x={x[0]:.2f}, y={x[1]:.2f}")\nprint(f"Verify: A@x = {A @ x}  (should be {b})")\n\n# 2. Normal equation — Linear Regression\nnp.random.seed(0)\nX_raw = np.random.randn(20,1)\ny = 3 * X_raw[:,0] + 2 + np.random.randn(20) * 0.5\nX = np.hstack([np.ones((20,1)), X_raw])   # add bias column\n\n# Normal equation\nw = np.linalg.solve(X.T @ X, X.T @ y)\nprint(f"\\nNormal equation weights:")\nprint(f"  bias={w[0]:.4f}  slope={w[1]:.4f}")\nprint(f"  (true: bias≈2.0  slope≈3.0)")\n\n# 3. Overdetermined system (least squares)\nA_over = np.array([[1,1],[1,2],[1,3],[1,4]])\nb_over = np.array([2.1, 4.0, 5.9, 8.2])\nw_ls, _, _, _ = np.linalg.lstsq(A_over, b_over, rcond=None)\nprint(f"\\nLeast-squares fit: intercept={w_ls[0]:.3f} slope={w_ls[1]:.3f}")`,
  questions:[
    q('What does np.linalg.solve(A, b) compute?',[{id:'a',text:'A@b'},{id:'b',text:'A⁻¹ only'},{id:'c',text:'The vector x such that A@x=b'},{id:'d',text:'The determinant'}],'c','solve uses LU decomposition to find x satisfying Ax=b more stably than inv(A)@b.',0),
    q('When does a system Ax=b have no solution?',[{id:'a',text:'When A is invertible'},{id:'b',text:'When the equations are inconsistent — planes do not share a common point'},{id:'c',text:'When A is square'},{id:'d',text:'When b=0'}],'b','Inconsistent systems (contradictory constraints) have no solution.',1),
    q('What is the Normal Equation in linear regression?',[{id:'a',text:'y=Wx+b'},{id:'b',text:'w=(XᵀX)⁻¹Xᵀy — the closed-form least-squares solution'},{id:'c',text:'dL/dw=0'},{id:'d',text:'w=X⁻¹y'}],'b','The Normal Equation solves the least-squares problem analytically without iteration.',2),
    q('Why is np.linalg.solve preferred over np.linalg.inv(A)@b?',[{id:'a',text:'solve is faster and more numerically stable'},{id:'b',text:'inv is not defined for square matrices'},{id:'c',text:'solve works on non-square matrices'},{id:'d',text:'Both are identical'}],'a','solve uses LU decomposition — avoids computing the explicit inverse, which amplifies floating-point errors.',3),
    q('What is an overdetermined system?',[{id:'a',text:'More unknowns than equations'},{id:'b',text:'More equations than unknowns — typically no exact solution, use least squares'},{id:'c',text:'A system with a unique solution'},{id:'d',text:'A system with infinite solutions'}],'b','Overdetermined means more constraints than variables — least squares finds the best-fit approximation.',4),
    q('What does np.linalg.lstsq(A,b) solve?',[{id:'a',text:'The exact solution of Ax=b'},{id:'b',text:'The least-squares solution minimising ‖Ax-b‖²'},{id:'c',text:'The system only if it is consistent'},{id:'d',text:'The eigenvalues of A'}],'b','lstsq finds x that minimises residuals — standard for fitting linear models.',5),
    q('In Gaussian elimination, what is the augmented matrix?',[{id:'a',text:'A transposed'},{id:'b',text:'[A | b] — coefficients and RHS combined'},{id:'c',text:'A inverted'},{id:'d',text:'A@b'}],'b','[A|b] puts all information in one matrix for row reduction.',6),
    q('What is a homogeneous system?',[{id:'a',text:'A=I'},{id:'b',text:'Ax=0 — zero RHS'},{id:'c',text:'All coefficients equal'},{id:'d',text:'A is diagonal'}],'b','Homogeneous systems Ax=0 always have the trivial solution x=0; non-trivial solutions exist when det(A)=0.',7),
    q('Why is the Normal Equation sometimes avoided in large-scale ML?',[{id:'a',text:'It requires a GPU'},{id:'b',text:'Computing (XᵀX)⁻¹ is O(n³) — too slow for large feature dimensions'},{id:'c',text:'It only works for binary classification'},{id:'d',text:'It does not minimise MSE'}],'b','Matrix inversion scales cubically — gradient descent is preferred for high-dimensional problems.',8),
    q('What rank is a 3×3 matrix with all rows identical?',[{id:'a',text:'3'},{id:'b',text:'2'},{id:'c',text:'1'},{id:'d',text:'0'}],'c','Identical rows are all multiples of one row — only 1 linearly independent row.',9),
  ]},

  {slug:'af-noob-19-eigenvalues',title:'Eigenvalues & Eigenvectors',description:'Computing eigenvalues/vectors, geometric interpretation, diagonalisation, and the role of PCA in dimensionality reduction for ML.',orderIndex:19,xpReward:75,difficulty:'BEGINNER',tier:'NOOB',language:'python',
  content:`# Chapter 19 — Eigenvalues & Eigenvectors\n\n## Definition\n\nFor a square matrix A, an eigenvector v and eigenvalue λ satisfy:\n\n$$Av = \\lambda v$$\n\nA only SCALES v — it does not rotate it.\n\n## Computing Them\n\n\`\`\`python\nvals, vecs = np.linalg.eig(A)\n\`\`\`\n\n## Geometric Meaning\n\n- Eigenvectors are the **special directions** a matrix only stretches\n- Eigenvalues are the **stretch factors**\n\n## PCA Connection\n\n1. Compute covariance matrix C = XᵀX / (n-1)\n2. Compute eigenvectors of C\n3. Sort by eigenvalue (largest = most variance)\n4. Project data onto top-k eigenvectors\n\nThis IS PCA. The eigenvectors are principal components.\n\n## Applications in AI\n\n- PCA for dimensionality reduction\n- Google PageRank (dominant eigenvector)\n- Spectral clustering\n- Understanding what neural networks learn`,
  codeExample:`import numpy as np\n\n# 1. Eigen decomposition\nA = np.array([[3,1],[1,3]], dtype=float)\nvals, vecs = np.linalg.eig(A)\nprint("Matrix A:")\nprint(A)\nprint(f"Eigenvalues  : {vals}")\nprint(f"Eigenvectors :\\n{vecs}")\n\n# Verify: A @ v = λ @ v\nfor i in range(len(vals)):\n    v = vecs[:,i]\n    lam = vals[i]\n    lhs = A @ v\n    rhs = lam * v\n    print(f"  λ={lam:.1f}: Av={np.round(lhs,4)}  λv={np.round(rhs,4)}  match={np.allclose(lhs,rhs)}")\n\n# 2. PCA from scratch\nnp.random.seed(42)\ndata = np.random.randn(100,3)\ndata[:,1] = data[:,0]*0.9 + np.random.randn(100)*0.2   # feature2 ≈ feature1\n\nC = np.cov(data.T)   # 3×3 covariance\nevals, evecs = np.linalg.eigh(C)  # symmetric → real eigenvalues\nidx = np.argsort(evals)[::-1]    # sort descending\nevecs = evecs[:,idx]\nevals = evals[idx]\n\nprint(f"\\nCovariance eigenvalues: {np.round(evals,4)}")\nprint(f"Variance explained: {np.round(evals/evals.sum()*100,1)}%")\n\ndata_2d = data @ evecs[:,:2]\nprint(f"Projected to 2D: {data_2d.shape}")`,
  questions:[
    q('What condition must v and λ satisfy for them to be an eigenvector/eigenvalue of A?',[{id:'a',text:'A+v=λ'},{id:'b',text:'Av=λv — A only scales v, not rotates it'},{id:'c',text:'Av=λ'},{id:'d',text:'vA=λv'}],'b','Av=λv: A transforms v by scaling it by λ — the direction is preserved.',0),
    q('What does a larger eigenvalue indicate in PCA?',[{id:'a',text:'More noise'},{id:'b',text:'More variance is explained by that principal component'},{id:'c',text:'Fewer data points'},{id:'d',text:'Higher correlation between features'}],'b','Eigenvalues of the covariance matrix equal the variance in each principal component direction.',1),
    q('Why is the covariance matrix used in PCA?',[{id:'a',text:'It is always symmetric'},{id:'b',text:'Its eigenvectors point in the directions of maximum variance in the data'},{id:'c',text:'It is easier to invert'},{id:'d',text:'It removes noise'}],'b','Cov matrix eigenvectors = principal directions; eigenvalues = variance in each direction.',2),
    q('What does np.linalg.eig return?',[{id:'a',text:'Only eigenvalues'},{id:'b',text:'A tuple (eigenvalues, eigenvector matrix)'},{id:'c',text:'The determinant and trace'},{id:'d',text:'The inverse and transpose'}],'b','eig returns (vals, vecs) — vals[i] corresponds to vecs[:,i].',3),
    q('In PCA, what does projecting data onto the top-k eigenvectors achieve?',[{id:'a',text:'Makes data zero-mean'},{id:'b',text:'Reduces dimensions to k while retaining maximum variance'},{id:'c',text:'Normalises feature scales'},{id:'d',text:'Removes outliers'}],'b','Projecting onto top-k principal components compresses data to k-D with minimal information loss.',4),
    q('A 3×3 matrix has how many eigenvalues?',[{id:'a',text:'1'},{id:'b',text:'2'},{id:'c',text:'3'},{id:'d',text:'Depends on rank'}],'c','An n×n matrix has exactly n eigenvalues (counting multiplicity) over the complex numbers.',5),
    q('What does np.linalg.eigh do differently from eig?',[{id:'a',text:'Works on non-square matrices'},{id:'b',text:'Optimised for real symmetric matrices — returns real eigenvalues in sorted order'},{id:'c',text:'Returns only the largest eigenvalue'},{id:'d',text:'Computes eigenvectors only'}],'b','eigh exploits symmetry for speed and numerical accuracy — always use it for covariance matrices.',6),
    q('If λ=0 for a matrix, what does this imply?',[{id:'a',text:'The matrix is the identity'},{id:'b',text:'The matrix is singular (not invertible) — det=0'},{id:'c',text:'All rows are identical'},{id:'d',text:'The matrix is diagonal'}],'b','An eigenvalue of 0 means det(A)=0 — the matrix collapses some direction to zero.',7),
    q('Google PageRank uses the dominant eigenvector of which matrix?',[{id:'a',text:'The covariance matrix'},{id:'b',text:'The web link adjacency matrix'},{id:'c',text:'The Hessian of the loss'},{id:'d',text:'The identity matrix'}],'b','PageRank is the principal eigenvector of the stochastic web link transition matrix.',8),
    q('Why do we sort eigenvalues in descending order for PCA?',[{id:'a',text:'NumPy requires it'},{id:'b',text:'Largest eigenvalues correspond to directions of most variance — most informative features first'},{id:'c',text:'To speed up computation'},{id:'d',text:'To ensure positive values'}],'b','Selecting top-k eigenvectors by eigenvalue magnitude captures the most variance.',9),
  ]},

  {slug:'af-noob-20-linalg-applications',title:'Linear Algebra Applications in ML',description:'How matrix operations underpin neural networks, PCA in practice, cosine similarity in recommenders, and SVD for collaborative filtering.',orderIndex:20,xpReward:75,difficulty:'BEGINNER',tier:'NOOB',language:'python',
  content:`# Chapter 20 — Linear Algebra Applications in ML\n\n## The Bridge from Math to Models\n\nEvery major ML algorithm maps to a linear algebra operation.\n\n| ML Concept | Linear Algebra Operation |\n|------------|-------------------------|\n| Dense layer | Z = WX + b |\n| Attention | softmax(QKᵀ/√d)V |\n| PCA | Eigendecomposition |\n| SVD for recommenders | UV decomposition |\n| Cosine similarity | Normalised dot product |\n\n## SVD for Matrix Factorisation\n\n$$A \\approx U \\Sigma V^T$$\n\nIn collaborative filtering, a user-item rating matrix is factorised into user and item embeddings.\n\n## QR Decomposition\n\nA = QR where Q is orthonormal, R is upper triangular. Used in numerical solvers and the Gram-Schmidt process.\n\n## Condition Number\n\ncond(A) = ‖A‖·‖A⁻¹‖. High condition number → ill-conditioned system → numerical instability in training.`,
  codeExample:`import numpy as np\n\nnp.random.seed(0)\n\n# 1. Neural network forward pass — full batch\nbatch, d_in, d_h, d_out = 8, 5, 4, 3\nX  = np.random.randn(batch, d_in)\nW1 = np.random.randn(d_in, d_h)  * 0.1\nb1 = np.zeros(d_h)\nW2 = np.random.randn(d_h, d_out) * 0.1\nb2 = np.zeros(d_out)\n\nA1 = np.maximum(0, X @ W1 + b1)   # ReLU hidden\nZ2 = A1 @ W2 + b2                  # output logits\nprint(f"Input {X.shape} → hidden {A1.shape} → out {Z2.shape}")\n\n# 2. SVD — matrix factorisation (recommender system)\nratings = np.array([[5,3,0,1],[4,0,0,1],[1,1,0,5],[0,0,4,4],[0,1,5,4]], dtype=float)\nU,S,Vt = np.linalg.svd(ratings, full_matrices=False)\nk=2  # keep top 2 singular values\nratings_approx = U[:,:k] @ np.diag(S[:k]) @ Vt[:k,:]\nprint(f"\\nRatings matrix (5 users × 4 items):\\n{ratings}")\nprint(f"Low-rank approx (k={k}):\\n{np.round(ratings_approx,1)}")\n\n# 3. Cosine similarity — item recommender\nitem1 = Vt[0]  # first item factor\nitem2 = Vt[1]\ncos = np.dot(item1,item2)/(np.linalg.norm(item1)*np.linalg.norm(item2))\nprint(f"\\nItem 1 factor: {np.round(item1,3)}")\nprint(f"Item 2 factor: {np.round(item2,3)}")\nprint(f"Cosine similarity: {cos:.4f}")`,
  questions:[
    q('What linear algebra operation does a dense neural network layer perform?',[{id:'a',text:'SVD decomposition'},{id:'b',text:'Z = W @ X + b — matrix multiplication plus bias'},{id:'c',text:'Eigendecomposition'},{id:'d',text:'QR factorisation'}],'b','Every dense/fully-connected layer is a matrix multiply followed by a bias add.',0),
    q('What does SVD decompose a matrix A into?',[{id:'a',text:'LU factors'},{id:'b',text:'QR factors'},{id:'c',text:'U, Σ, Vᵀ — left singular vectors, singular values, right singular vectors'},{id:'d',text:'Eigenvalues and eigenvectors'}],'c','A = UΣVᵀ: U (left), Σ (diagonal singular values), Vᵀ (right singular vectors).',1),
    q('In collaborative filtering, what do U and Vᵀ from SVD represent?',[{id:'a',text:'Noise components'},{id:'b',text:'User embeddings and item embeddings'},{id:'c',text:'Principal components'},{id:'d',text:'Gradient matrices'}],'b','Low-rank SVD factorises the ratings matrix into latent user and item factor vectors.',2),
    q('What is the attention mechanism formula in transformers?',[{id:'a',text:'softmax(Q@K.T / sqrt(d)) @ V'},{id:'b',text:'Q @ K @ V'},{id:'c',text:'softmax(Q @ V) @ K'},{id:'d',text:'W @ X + b'}],'a','Scaled dot-product attention: softmax(QKᵀ/√d)V — pure linear algebra.',3),
    q('What does a high condition number of matrix A indicate?',[{id:'a',text:'A is easy to invert'},{id:'b',text:'A is ill-conditioned — small input changes cause large output changes, leading to numerical instability'},{id:'c',text:'A is singular'},{id:'d',text:'A has full rank'}],'b','High condition number signals numerical sensitivity — gradients can explode/vanish.',4),
    q('In low-rank approximation A≈UₖΣₖVₖᵀ, what does reducing k do?',[{id:'a',text:'Increases accuracy'},{id:'b',text:'Reduces the approximation to fewer latent dimensions — lossy compression'},{id:'c',text:'Makes the matrix square'},{id:'d',text:'Removes negative values'}],'b','Smaller k = more compression = less detail retained; trade-off accuracy for dimensionality.',5),
    q('What is an orthonormal matrix Q?',[{id:'a',text:'A matrix where all elements are 0 or 1'},{id:'b',text:'A matrix whose columns are mutually perpendicular unit vectors: Qᵀ=Q⁻¹'},{id:'c',text:'A matrix with determinant 0'},{id:'d',text:'A matrix with equal rows'}],'b','Orthonormal: columns have unit length and are perpendicular — Qᵀ@Q = I.',6),
    q('Why is cosine similarity preferred over Euclidean distance in NLP embedding spaces?',[{id:'a',text:'It is faster to compute'},{id:'b',text:'It measures directional alignment, ignoring vector magnitude — captures semantic similarity'},{id:'c',text:'It works in high dimensions'},{id:'d',text:'Both B and C'}],'d','Cosine is direction-only and works well in high-dimensional sparse spaces like word embeddings.',7),
    q('What is the Gram-Schmidt process used for?',[{id:'a',text:'Gradient computation'},{id:'b',text:'Orthonormalising a set of vectors — constructing orthonormal basis'},{id:'c',text:'Matrix inversion'},{id:'d',text:'Eigenvalue computation'}],'b','Gram-Schmidt converts any linearly independent set into an orthonormal set — basis for QR.',8),
    q('Why is understanding linear algebra essential for AI research?',[{id:'a',text:'AI algorithms require linear algebra knowledge to debug and design'},{id:'b',text:'Every core operation (attention, convolution, gradient) is a matrix operation'},{id:'c',text:'To read and write research papers on neural architectures'},{id:'d',text:'All of the above'}],'d','Linear algebra IS the language of AI — all operations are tensor/matrix computations.',9),
  ]},
];

async function main() {
  const course = await prisma.course.findUnique({ where: { slug: COURSE_SLUG } });
  if (!course) throw new Error(`Course "${COURSE_SLUG}" not found`);
  for (const ch of CHAPTERS) {
    const existing = await prisma.chapter.findFirst({ where: { courseId: course.id, slug: ch.slug } });
    if (existing) { console.log(`⏭  Skip  ${ch.slug}`); continue; }
    const { questions, ...chapterData } = ch;
    const chapter = await prisma.chapter.create({ data: { ...chapterData, courseId: course.id } });
    await prisma.quiz.create({ data: { chapterId:chapter.id, title:`${ch.title} Quiz`, description:`Test your knowledge of ${ch.title}`, timeLimit:600, passingScore:70, xpReward:Math.round(ch.xpReward*0.8), questions:{ create: questions } } });
    console.log(`✅ Created ch ${ch.orderIndex}: ${ch.title}`);
  }
  console.log('\n🎉 AI Foundations NOOB Block 4 seeded!');
}
main().catch(e=>{console.error(e);process.exit(1);}).finally(()=>prisma.$disconnect());
